name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@v0.1.7 # Use the latest version
        with:
          host: 3.110.107.179
          username: ubuntu
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          port: 22
          script: |
            cd aws
            git pull
            npm install --legacy-peer-deps
            npm run build
            nohup npm run start > output.log 2>&1 &
