name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 3.110.107.179
          username: ubuntu
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          port: 22
          script: |
            # Navigate to your project folder
            cd ~/ci-cd

            # Pull the latest changes from GitHub
            git pull

               # Install dependencies
            npm install --legacy-peer-deps

            # Build the project
            npm run build

            # Check for PM2 processes and stop the existing one
            pm2 stop next-app || echo "No process to stop"

            # Start the app with PM2
            pm2 start npm --name "next-app" -- run start || (echo "Failed to start app" && exit 1)

            # Save PM2 process list
            pm2 save

            # Enable PM2 to restart on reboot
            pm2 startup systemd -u ubuntu --hp /home/ubuntu
